jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8080
   servlet:
      context-path: /Conductor_Elegido
      session:
         timeout: 21600s

spring:
   flyway:
      baselineOnMigrate: true
   datasource:
      driver-class-name: org.postgresql.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:postgresql://localhost:5432/conductor_elegido
      username: postgres
      password: root
      hikari:
         poolName: pool
